// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RideBikePlanifierBackEnd.Models;

namespace RideBikePlanifierBackEnd.Migrations
{
    [DbContext(typeof(RideBikePlanifierContext))]
    partial class RideBikePlanifierContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RideBikePlanifierBackEnd.Models.Usuario", b =>
                {
                    b.Property<string>("correoElectronico")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("apellido1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contrasenia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numeroEmergencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("padecimientos")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("correoElectronico");

                    b.ToTable("usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
